---
Style/FormatStringToken:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/FormatString:
  EnforcedStyle: percent

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/BracesAroundHashParameters:
  EnforcedStyle: braces

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - x
    - y
    - dx
    - dy
    - dt
    - to
    - id
    - io

Metrics/MethodLength:
  Max: 24

Metrics/AbcSize:
  Max: 50

Metrics/ParameterLists:
  Max: 6

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150
