# frozen_string_literal: true

require "rgame/common/collection_entity.rb"
require "rgame/common/collision_aspect.rb"
require "rgame/common/control_4way_aspect.rb"
require "rgame/common/draw_aspect.rb"
require "rgame/common/editor_aspect.rb"
require "rgame/common/gui.rb"
require "rgame/common/imagelayer_entity.rb"
require "rgame/common/map_entity.rb"
require "rgame/common/movement_aspect.rb"
require "rgame/common/position_aspect.rb"
require "rgame/common/queue_entity.rb"
require "rgame/common/restrict_aspect.rb"
require "rgame/common/root_entity.rb"
require "rgame/common/sprite_aspect.rb"
require "rgame/common/stack_entity.rb"
require "rgame/common/tilelayer_entity.rb"
require "rgame/common/timer_aspect.rb"
